apiVersion: v1
kind: Service
metadata:
  name: {{ include "xmtp-payer.fullname" . }}
  labels:
    {{- include "xmtp-payer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "xmtp-payer.selectorLabels" . | nindent 4 }}
