apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xmtpd.fullname" . }}-api
  labels:
    {{- include "xmtpd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "xmtpd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xmtpd.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/role: xmtpd-server-api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xmtpd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: contracts-config-volume
          configMap:
            name: {{ .Values.contractsConfig.configMapName | default (printf "%s-contracts-config" (include "xmtpd.fullname" .)) }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--replication.enable", "--metrics.enable", "--metrics.metrics-address=0.0.0.0"]
          {{- if (include "helpers.list-env-variables" .) }}
          env:
            - name: XMTPD_CONTRACTS_CONFIG_FILE_PATH
              value: /etc/xmtp/contracts.json
            {{ include "helpers.list-env-variables" . | indent 12 }}
          {{- end }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
            - name: metrics
              containerPort: 8008
          startupProbe:
            grpc:
              port: {{ .Values.service.targetPort }}
            failureThreshold: 3
            periodSeconds: 10
          livenessProbe:
            grpc:
              port: {{ .Values.service.targetPort }}
            failureThreshold: 3
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: contracts-config-volume
              mountPath: /etc/xmtp
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
