{{- if .Values.ingress.create -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "xmtpd.ingressName" . }}
  labels:
    {{- include "xmtpd.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- if .Values.ingress.tls.certIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.certIssuer }}
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ include "xmtpd.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls.secretName }}
  tls:
  - secretName: {{ .Values.ingress.tls.secretName }}
    hosts:
      - {{ .Values.ingress.host }}
  {{- end }}
{{- end }}
