apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xmtpd.fullname" . }}-sync
  labels:
    {{- include "xmtpd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "xmtpd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xmtpd.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xmtpd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: XMTPD_SYNC_ENABLE
              value: "true"
            - name: XMTPD_INDEXER_ENABLE
              value: "true"
            - name: XMTPD_METRICS_ENABLE
              value: "true"
            - name: XMTPD_METRICS_METRICS_ADDRESS
              value: "0.0.0.0"
            {{- include "helpers.list-env-variables" . | indent 12 }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8008
              scheme: HTTP
            failureThreshold: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8008
              scheme: HTTP
            failureThreshold: 3
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
