name: Test Charts

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23.1'
          go-version-file: go.mod
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      - name: Run Tests
        env:
          XMTPD_PAYER_PRIVATE_KEY:  ${{ secrets.XMTPD_PAYER_PRIVATE_KEY }}
          XMTPD_SIGNER_PRIVATE_KEY: ${{ secrets.XMTPD_SIGNER_PRIVATE_KEY }}
        run: go test -v ./...

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: results/